# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do |lane, options|
    puts '*** 准备执行任务 ***'
  end

  after_all do |lane, options|
    puts ">> end"
   end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :hah do
    puts '*** hello fastlane world ***'
  end

  desc "test method"
  lane :test do
    puts '>> exec test lane method'
  end
end
